services:
  adminer:
    image: adminer:5.3.0
    container_name: adminer
    restart: always
    ports:
    - "${ADMINER_PUBLISH_PORT}:${ADMINER_DEFAULT_PORT}"
    depends_on:
      - mysql
    env_file:
      - ./mysql/.env
    networks:
      - docker-dev-common

networks:
  docker-dev-common:
    external: true
