services:
  mysql:
    image: mysql:8.0.43-debian
    container_name: mysql
    env_file:
      - ./mysql/.env
    ports:
    - "${MYSQL_PUBLISH_PORT}:${MYSQL_DEFAULT_PORT}"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - docker-dev-common
volumes:
  mysql_data:

networks:
  docker-dev-common:
    external: true
