services:
  mysql:
    image: mysql:8.0.43-debian
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
    - "${MYSQL_PUBLISH_PORT}:${MYSQL_DEFAULT_PORT}"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - docker-dev-common
volumes:
  mysql_data:
